return function()
	local luaBits = require(script.Parent.luaBits)

	it("should give number of bits needed for integers", function()
		local bits = luaBits.bitsToRepresentInt(1)
		expect(bits).to.equal(1)
		bits = luaBits.bitsToRepresentInt(3)
		expect(bits).to.equal(2)
		bits = luaBits.bitsToRepresentInt(7)
		expect(bits).to.equal(3)
		bits = luaBits.bitsToRepresentInt(15)
		expect(bits).to.equal(4)
		bits = luaBits.bitsToRepresentInt(31)
		expect(bits).to.equal(5)
		bits = luaBits.bitsToRepresentInt(63)
		expect(bits).to.equal(6)
		bits = luaBits.bitsToRepresentInt(127)
		expect(bits).to.equal(7)
		bits = luaBits.bitsToRepresentInt(255)
		expect(bits).to.equal(8)
		bits = luaBits.bitsToRepresentInt(511)
		expect(bits).to.equal(9)
		bits = luaBits.bitsToRepresentInt(1023)
		expect(bits).to.equal(10)
	end)

	it("should encode and decode integers", function()
		local bitString = luaBits.integerToBitString(145, 8)
		local integer = luaBits.bitStringToInteger(bitString)
		expect(integer).to.equal(145)
	end)

	it("should compress and decompress 8 bit data", function()
		local bitString = luaBits.integerToBitString(145, 8)
		local compressedBitString, padding = luaBits.compressBitString(bitString)
		local decompressedBitString = luaBits.decompressBitString(compressedBitString, false, padding)
		local integer = luaBits.bitStringToInteger(decompressedBitString)
		expect(integer).to.equal(145)

		bitString = luaBits.integerToBitString(1000, 10)
		compressedBitString, padding = luaBits.compressBitString(bitString)
		decompressedBitString = luaBits.decompressBitString(compressedBitString, false, padding)
		integer = luaBits.bitStringToInteger(decompressedBitString)
		expect(integer).to.equal(1000)
	end)

	it("should compress and decompress 6 bit data", function()
		local bitString = luaBits.integerToBitString(30, 6)
		local compressedBitString, padding = luaBits.compressBitString(bitString, true)
		local decompressedBitString = luaBits.decompressBitString(compressedBitString, true, padding)
		local integer = luaBits.bitStringToInteger(decompressedBitString)
		expect(integer).to.equal(30)

		bitString = luaBits.integerToBitString(1000, 10)
		compressedBitString, padding = luaBits.compressBitString(bitString, true)
		decompressedBitString = luaBits.decompressBitString(compressedBitString, true, padding)
		integer = luaBits.bitStringToInteger(decompressedBitString)
		expect(integer).to.equal(1000)
	end)

	local voxelData, voxelBitString, voxelSpec, sizeCallbacks = require(script.Parent.voxelData)

	it("should encode and decode complex data structures", function()
		--[[local compressedData, padding = luaBits.compressBitString(voxelBitString)
		local decompressedData = luaBits.decompressBitString(compressedData, padding)]]
		local deserializedData = luaBits.deserializeBitString(voxelBitString, voxelSpec, sizeCallbacks)
		expect(deserializedData).to.deep.equal(voxelData)
	end)
end